SELECT USER_ID,NICKNAME,SUM(PRICE) AS TOTAL_SALES from USED_GOODS_BOARD,USED_GOODS_USER
WHERE USED_GOODS_BOARD.WRITER_ID = USED_GOODS_USER.USER_ID AND USED_GOODS_BOARD.STATUS = "DONE"
GROUP BY USED_GOODS_BOARD.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC